
import './globals.css'


export const metadata = {
  title: 'Quiz app',
  description: 'Generated by Dev Oluyemi',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
